# Image de base
FROM postgres:17.6

# Mot de passe ROOT du serveur de base de données
ENV POSTGRES_ROOT_PASSWORD=root
# Nom de la base de données qui sera créée au 1er démarrage du conteneur
ENV POSTGRES_DB=mydatabase
# Nom d'utilisateur pour se connecter à la base de données
ENV POSTGRES_USER=Mike
# Mot de passe pour se connecter à la base de données
ENV POSTGRES_PASSWORD=root

